{
 "title": "Gossip Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Gossip MPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gossip_by_type_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MPS by Type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(gossip_by_type_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gossip MPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(gossip_by_type_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MPS by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(gossip_by_type_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unique Observations / Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(gossip_observations_unique_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique VAAs / Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(gossip_vaas_unique_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OPS by Chain",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (chain_name) (rate(gossip_observations_by_guardian_per_chain_total[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OPS by Guardian",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (guardian_name) (rate(gossip_observations_by_guardian_per_chain_total[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OPS By Guardian and Chain",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(gossip_observations_by_guardian_per_chain_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}